version: "3.8"

services:
  gema:
    image: registry.gaeni.org/gema/ai:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.gema.rule=Host(`gema-ai.gaeni.org`)"
        - "traefik.http.routers.gema.entrypoints=https"
        - "traefik.http.routers.gema.tls=true"
        - "traefik.http.routers.gema.tls.certresolver=le"
        - "traefik.http.services.gema.loadbalancer.server.port=8501"
    environment:
      OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
      SERPER_API_KEY: "${{ secrets.SERPER_API_KEY }}"
      OPENAI_MODEL: "gpt-4o"
      TEMPERATURE: "0.1"
      MAX_TOKENS: "2000"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
